#!/bin/sh

for insert in L A B R S V
do
	for order in A P R
	do
		for size in 5000
		do
			echo ""
			echo "Test: ./tlab $size $order $insert"
			echo "t" | ./tlab $size $order $insert | grep -v Tree
		done
	done
done
