#!/bin/sh

cat /dev/null > log
for size in $(seq 5 5 100; seq 200 100 900; seq 1000 1000 100000); do
	echo === Testing for $order input, size $size === >> log
	for i in 1 2 3 4 5
	do
		sum += $({ ./gen $size R | /usr/bin/time --format="%U" ./sortB > /dev/null ; } 2>>)
	done
	
	echo "" >> log
done

#do
	#for order in random sorted reverse
	#do
#		echo === Testing for $order input, size $size === >> log
		#for i in 1 2 3 4 5
		#do
	#		case $order in
	#		random) flag="R" ;;
	#		sorted) flag="A" ;;
	#		reverse) flag="D" ;;
	#		esac
	#		{ ./gen $size $flag | time ./sort > /dev/null ; } 2>> log
	#	done
	#	echo "" >> log
	#done
#done

#cat /dev/null > log
#for size in 100 1000 10000 100000 1000000
#do
	#for order in random sorted reverse
	#do
#		echo === Testing for $order input, size $size === >> log
		#for i in 1 2 3 4 5
		#do
	#		case $order in
	#		random) flag="R" ;;
	#		sorted) flag="A" ;;
	#		reverse) flag="D" ;;
	#		esac
	#		{ ./gen $size $flag | time ./sort > /dev/null ; } 2>> log
	#	done
	#	echo "" >> log
	#done
#done
